### ISSUE TITLE
Moderator configuration

### ISSUE THREAD

**Issue by Fadgiras** [readthedocs-fr/pvc#14]
Add a command allowing to set a moderator role.
It should allow moderators to connect and see to the channels which are created by the bot.
And it maybe should allow the given moderators to modify the settings of a given channel.

**Comment by Methqphore** [comment]
> Add a command allowing to set a moderator role.
> It should allow moderators to connect and see to the channels which are created by the bot.
> And it maybe should allow the given moderators to modify the settings of a given channel.

this command must be accessible only for the administrators of the server, like the `$setchannel` command

**Comment by TNtube** [comment]
Because of wtf discord, we don't need to implement this anymore, the only thing simply add the desired permissions to the category, and they will be applied to the channel.
